development:
  morphology: stem_en
  morphology: stem_ru
  min_prefix_len: 3
  mysql41: 9312

production:
  mem_limit: 128M
  enable_star: true
  min_prefix_len: 3
  mysql41: 9312

test:
  morphology: stem_en
  morphology: stem_ru
  min_prefix_len: 3
  mysql41: 9307
